# Generated by Django 4.1.2 on 2022-11-11 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='content',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='answer',
            name='content',
            field=models.CharField(max_length=200),
        ),
    ]
